export type Hospital = {
  slug: string;
  name: string;
  location: string;
  established: string;
  beds: string;
  city: string;
  image: string;
  summary: string;
  profile: HospitalProfile;
};

export type HospitalProfile = {
  about: string[];
  departments: string[];
  specialities: string[];
  facilities: string[];
  awards: string[];
  procedures: string[];
};

const createHospitalProfile = (hospital: {
  name: string;
  location: string;
  established: string;
  beds: string;
  summary: string;
  departments: string[];
  specialities: string[];
  facilities: string[];
  awards: string[];
  procedures: string[];
}): HospitalProfile => ({
  about: [
    `${hospital.name} is a leading healthcare institution located in ${hospital.location}. Established in ${hospital.established}, the hospital has grown into a trusted destination for medical care, equipped with ${hospital.beds} beds and advanced medical infrastructure.`,
    hospital.summary,
  ],
  departments: hospital.departments,
  specialities: hospital.specialities,
  facilities: hospital.facilities,
  awards: hospital.awards,
  procedures: hospital.procedures,
});

export const hospitals: Hospital[] = [
  {
    slug: "max-saket",
    name: "Max Super Speciality Hospital, Saket",
    location: "New Delhi",
    established: "2006",
    beds: "539",
    city: "Delhi",
    image: "/images/hospitals/max-saket.jpg",
    summary:
      "Max Super Specialty Hospital is widely considered as one of the best hospitals in India, split into two blocks with experts who have treated over 34 lakh patients across 32 specialities.",
    profile: createHospitalProfile({
      name: "Max Super Speciality Hospital, Saket",
      location: "New Delhi",
      established: "2006",
      beds: "539",
      summary:
        "The hospital has international accreditation by JCI and NABH for providing high-quality patient safety and care. It offers the benefit of integrated medical care in a multidisciplinary setting, provided by a faculty of highly qualified doctors, nurses, and healthcare professionals. The hospital is a hub for complex procedures such as targeted cancer treatments, heart surgeries, neurovascular intervention, orthopedic surgeries, liver and kidney transplants, and fertility treatments.",
      departments: [
        "Cardiac Sciences",
        "Oncology",
        "Neurosciences",
        "Orthopedics",
        "Transplant Services",
        "Gastroenterology",
      ],
      specialities: [
        "Cardiac Surgery",
        "Medical Oncology",
        "Radiation Oncology",
        "Neurovascular Intervention",
        "Liver Transplant",
        "Kidney Transplant",
        "Bone Marrow Transplant",
        "Orthopedic Surgery",
        "Fertility Treatment",
        "Bariatric Surgery",
      ],
      facilities: [
        "539 Beds",
        "JCI & NABH Accredited",
        "Advanced Diagnostic Imaging",
        "24/7 Emergency Services",
        "Intensive Care Units",
        "Robotic Surgery Suite",
        "Blood Bank",
        "Pharmacy",
      ],
      awards: [
        "JCI Accreditation",
        "NABH Accreditation",
        "Recognized as one of India's top multi-speciality hospitals",
      ],
      procedures: [
        "Heart Bypass Surgery",
        "Angioplasty",
        "Chemotherapy",
        "Radiation Therapy",
        "Brain Tumor Surgery",
        "Spine Surgery",
        "Knee Replacement",
        "Hip Replacement",
        "Liver Transplant",
        "Kidney Transplant",
      ],
    }),
  },
  {
    slug: "aakash-healthcare",
    name: "Aakash Healthcare Super Speciality Hospital",
    location: "New Delhi",
    established: "2010",
    beds: "230",
    city: "Delhi",
    image: "/images/hospitals/aakash-healthcare.jpg",
    summary:
      "A leading center for Orthopedics and Joint Replacement with 15 dialysis units and 70 beds for critical care, accredited by NABH and NABL.",
    profile: createHospitalProfile({
      name: "Aakash Healthcare Super Speciality Hospital",
      location: "New Delhi",
      established: "2010",
      beds: "230",
      summary:
        "The hospital ranks among the best hospitals for knee transplants in Delhi and is known for its leading care in orthopedics and joint replacement surgery. It has comprehensive services and centres of excellence such as cardiology, orthopedics & joint replacement, general and minimally invasive surgery, ophthalmology, neurology and neurosurgery, and renal sciences. The hospital also has a 24/7 trauma and emergency centre, a blood bank with advanced Neonatal and Pediatric ICU.",
      departments: [
        "Orthopedics",
        "Cardiology",
        "Neurology",
        "Ophthalmology",
        "Renal Sciences",
        "General Surgery",
      ],
      specialities: [
        "Joint Replacement Surgery",
        "Knee Transplant",
        "Minimally Invasive Surgery",
        "Cardiac Care",
        "Neuro Sciences",
        "Dialysis Services",
      ],
      facilities: [
        "230 Beds",
        "70 Critical Care Beds",
        "15 Dialysis Units",
        "24/7 Trauma & Emergency Centre",
        "NABH & NABL Accredited",
        "Blood Bank",
        "Neonatal & Pediatric ICU",
        "Advanced Diagnostic Lab",
      ],
      awards: [
        "NABH Accreditation",
        "NABL Accreditation",
      ],
      procedures: [
        "Knee Replacement",
        "Hip Replacement",
        "Knee Transplant",
        "Cataract Surgery",
        "Neurology Consultation",
        "Dialysis",
        "General Surgery",
      ],
    }),
  },
  {
    slug: "apollo-delhi",
    name: "Indraprastha Apollo Hospital",
    location: "New Delhi",
    established: "1995",
    beds: "710",
    city: "Delhi",
    image: "/images/hospitals/apollo-delhi.jpg",
    summary:
      "India's first corporate hospital, acclaimed for pioneering the private healthcare revolution. Trusted by more than 150 million people from 140 countries.",
    profile: createHospitalProfile({
      name: "Indraprastha Apollo Hospital",
      location: "New Delhi",
      established: "1995",
      beds: "710",
      summary:
        "Established in 1983 by Dr. Prathap C Reddy, Apollo Hospitals was the first corporate hospital in India and is acclaimed for pioneering the private healthcare revolution. The government of India has honored Apollo Hospitals by issuing a special stamp to honor its significant impact on healthcare. Apollo Hospitals has gained the trust of more than 150 million people from 140 different countries. The hospital has telemedicine facilities for international patients, health insurance services, and a research foundation. Apollo has campaigned in various social initiatives for underprivileged children, such as SACHi, SAHI, and CURE Foundation.",
      departments: [
        "Cardiology",
        "Oncology",
        "Neurology",
        "Orthopedics",
        "Transplant Services",
        "Gastroenterology",
      ],
      specialities: [
        "Proton Therapy",
        "Cardiac Surgery",
        "Liver Transplant",
        "Kidney Transplant",
        "Bone Marrow Transplant",
        "Cancer Care",
        "Pediatric Care",
        "Robotic Surgery",
      ],
      facilities: [
        "710 Beds",
        "Proton Therapy Center",
        "Telemedicine Facilities",
        "24/7 Emergency",
        "Advanced ICU",
        "Blood Bank",
        "Pharmacy",
        "International Patient Services",
      ],
      awards: [
        "Government of India Special Stamp",
        "Asia's Leading Healthcare Provider",
        "First Proton Therapy in South East Asia",
      ],
      procedures: [
        "Heart Bypass Surgery",
        "Angioplasty",
        "Liver Transplant",
        "Kidney Transplant",
        "Bone Marrow Transplant",
        "Proton Therapy for Cancer",
        "Knee Replacement",
        "Hip Replacement",
      ],
    }),
  },
  {
    slug: "blk-max",
    name: "BLK Max Super Speciality Hospital",
    location: "New Delhi",
    established: "1959",
    beds: "650",
    city: "Delhi",
    image: "/images/hospitals/blk-max.jpg",
    summary:
      "The largest part of India's healthcare sector, spread over 6,50,000 sq. ft., with 650 beds, 22 operating theatres, and over 1,500 healthcare professionals.",
    profile: createHospitalProfile({
      name: "BLK Max Super Speciality Hospital",
      location: "New Delhi",
      established: "1959",
      beds: "650",
      summary:
        "BLK-Max Super Specialty Hospital is the largest part of India's healthcare sector, spread over 6,50,000 sq. ft. The hospital is equipped with 650 beds, including 162 specially designed for critical care. There are 22 operating theaters that can be adapted for various types of surgery. The hospital has more than 1,500 healthcare professionals, including 150 highly respected specialists from around the world. It is India's first private hospital equipped with a dual console robotic system and a center for advanced sports rehabilitation.",
      departments: [
        "Cardiology",
        "Oncology",
        "Neurosciences",
        "Orthopedics",
        "Transplant Services",
        "Gastroenterology",
      ],
      specialities: [
        "Robotic Surgery",
        "Cardiac Sciences",
        "Cancer Care",
        "Neurology & Neurosurgery",
        "Orthopedics & Joint Replacement",
        "Liver & Kidney Transplant",
        "Sports Rehabilitation",
        "Spine Surgery",
      ],
      facilities: [
        "650 Beds",
        "162 Critical Care Beds",
        "22 Operating Theatres",
        "Dual Console Robotic System",
        "Advanced Sports Rehabilitation Center",
        "JCI & NABH Accredited",
        "Advanced Imaging (CT, MRI, PET)",
        "24/7 Emergency Services",
      ],
      awards: [
        "JCI Accreditation",
        "NABH Accreditation",
        "India's first private hospital with dual console robotic system",
      ],
      procedures: [
        "Robotic Surgery",
        "Heart Surgery",
        "Cancer Treatment",
        "Brain Surgery",
        "Spine Surgery",
        "Knee & Hip Replacement",
        "Liver Transplant",
        "Kidney Transplant",
      ],
    }),
  },
  {
    slug: "dharamshila-narayana",
    name: "Dharamshila Narayana Superspeciality Hospital",
    location: "New Delhi",
    established: "1994",
    beds: "191",
    city: "Delhi",
    image: "/images/hospitals/dharamshila-narayana.jpg",
    summary:
      "Leading hospital specializing in cancer treatment for over two decades, merged with Narayana Health in 2017. JCI and CAP accredited.",
    profile: createHospitalProfile({
      name: "Dharamshila Narayana Superspeciality Hospital",
      location: "New Delhi",
      established: "1994",
      beds: "191",
      summary:
        "One of the leading hospitals in New Delhi, specializing in cancer treatment for over two decades. In 2017, it merged with Narayana Health, the largest chain of multispecialty hospitals in India. It has JCI and CAP accreditations. The hospital has India's first and world-class blood and stem cell transplant facilities, including a 21-bed BMT center. It has received the Managing the Best Human Experience Award and holds a Guinness World Record for the Most Electrocardiogram Tests in 24 hours.",
      departments: [
        "Oncology",
        "Cardiac Sciences",
        "Neurology & Neurosurgery",
        "Nephrology & Urology",
        "Orthopedics",
        "Bone Marrow Transplantation",
      ],
      specialities: [
        "Cancer Treatment",
        "Bone Marrow Transplant",
        "Cardiac Surgery",
        "Neurology",
        "Kidney Transplant",
        "Joint Replacement",
        "Emergency Medicine",
      ],
      facilities: [
        "191 Beds",
        "42-bed ICU",
        "19-bed HDU",
        "7 State-of-the-art Operating Theatres",
        "21-bed BMT Center",
        "JCI & CAP Accredited",
        "Linear Accelerators",
        "PET CT Scan",
      ],
      awards: [
        "JCI Accreditation",
        "CAP Accreditation",
        "Guinness World Record for Most ECG Tests in 24 Hours",
        "Managing the Best Human Experience Award",
      ],
      procedures: [
        "Chemotherapy",
        "Radiation Therapy",
        "Bone Marrow Transplant",
        "Heart Surgery",
        "Brain Tumor Surgery",
        "Kidney Transplant",
        "Knee Replacement",
        "Hip Replacement",
      ],
    }),
  },
  {
    slug: "fortis-escorts",
    name: "Fortis Escorts Heart Institute",
    location: "New Delhi",
    established: "1988",
    beds: "310",
    city: "Delhi",
    image: "/images/hospitals/fortis-escorts.jpg",
    summary:
      "Prestigious multispeciality hospital recognized globally for remarkable work in cardiac care, with NABH, NABL, and Green OT certification.",
    profile: createHospitalProfile({
      name: "Fortis Escorts Heart Institute",
      location: "New Delhi",
      established: "1988",
      beds: "310",
      summary:
        "Fortis Escorts, Okhla Road, New Delhi, is a prestigious multispeciality hospital recognized globally for its remarkable work in cardiac care. The hospital has been awarded Best Private Cardiac Hospital in India multiple times. Fortis Escort has performed its first AUTO LIVER Transplant in North India, the fastest hip replacement in just 18 minutes. The hospital provides extensive advanced cardiac care in complex angioplasties, cardiac pacing, adult cardiac surgery, heart transplant, robotics, and minimally invasive cardiac surgery. It also specializes in gastrointestinal, pancreatic, and liver disorders.",
      departments: [
        "Cardiology",
        "Cardiac Surgery",
        "Gastroenterology",
        "Nephrology",
        "Orthopedics",
        "Liver Transplant",
      ],
      specialities: [
        "Advanced Cardiac Care",
        "Heart Transplant",
        "Liver Transplant",
        "Kidney Transplant",
        "Joint Replacement",
        "Spine Surgery",
        "Robotic Surgery",
        "Minimally Invasive Cardiac Surgery",
      ],
      facilities: [
        "310 Beds",
        "NABH & NABL Accredited",
        "Green OT Certification",
        "Advanced Cardiac Cath Lab",
        "24/7 Emergency Services",
        "Blood Bank",
        "ICU & Critical Care",
      ],
      awards: [
        "Best Private Cardiac Hospital in India (The Week Magazine, 2014-2024)",
        "Best Cardiology Hospital (2018, 2021-2024)",
        "Green OT Certification (Bureau Veritas, France)",
        "LIMCA Book of Records for Fastest Hip Replacement",
      ],
      procedures: [
        "Heart Bypass Surgery",
        "Angioplasty & Stenting",
        "Heart Valve Replacement",
        "Heart Transplant",
        "TAVR Procedure",
        "Liver Transplant",
        "Kidney Transplant",
        "Knee & Hip Replacement",
      ],
    }),
  },
  {
    slug: "fortis-memorial",
    name: "Fortis Memorial Research Institute",
    location: "Gurugram",
    established: "2013",
    beds: "330",
    city: "Gurugram",
    image: "/images/hospitals/fortis-memorial.jpg",
    summary:
      "Premier multi-super-speciality quaternary care hospital spread across an 11-acre campus with advanced technologies and world-class infrastructure.",
    profile: createHospitalProfile({
      name: "Fortis Memorial Research Institute",
      location: "Gurugram",
      established: "2013",
      beds: "330",
      summary:
        "Fortis Memorial Research Institute (FMRI) is located in Gurgaon, established in 2013, and designed as a premier multi-super-speciality quaternary care hospital. The BMT Bone Marrow Transplant program has completed over 1500 bone marrow transplants, making it the largest BMT program in North India. The Fortis Cancer Institute (FCI) brings treatments by a wide range of experts in surgical oncology, medical oncology, and radiation oncology. The Department of Neurosurgery at FMRI has successfully performed over 30,000 complex surgeries and is equipped with Gamma Knife Esprit, the first of its kind in South Asia.",
      departments: [
        "Oncology",
        "Neurosurgery",
        "Cardiology",
        "Orthopedics",
        "Transplant Services",
        "Gastroenterology",
      ],
      specialities: [
        "Bone Marrow Transplant",
        "Cancer Care",
        "Neurosurgery",
        "Cardiac Sciences",
        "Liver Transplant",
        "Kidney Transplant",
        "Robotic Surgery",
        "Gamma Knife Radiosurgery",
      ],
      facilities: [
        "330 Beds",
        "11-acre Campus",
        "Gamma Knife Esprit",
        "Advanced Radiation Oncology",
        "BMT Unit (1500+ transplants)",
        "24/7 Emergency",
        "Advanced Diagnostic Imaging",
        "Robotic Surgery Suite",
      ],
      awards: [
        "Largest BMT program in North India",
        "First Gamma Knife Esprit in South Asia",
      ],
      procedures: [
        "Bone Marrow Transplant",
        "Chemotherapy & Radiation",
        "Brain Tumor Surgery",
        "Gamma Knife Radiosurgery",
        "Heart Surgery",
        "Liver Transplant",
        "Kidney Transplant",
        "Spine Surgery",
      ],
    }),
  },
  {
    slug: "manipal-dwarka",
    name: "Manipal Hospital Dwarka",
    location: "New Delhi",
    established: "1953",
    beds: "380",
    city: "Delhi",
    image: "/images/hospitals/manipal-dwarka.jpg",
    summary:
      "Part of India's foremost multispeciality healthcare provider with a network of 37 hospitals in 19 cities, over 10,500 beds and 5600+ doctors.",
    profile: createHospitalProfile({
      name: "Manipal Hospital Dwarka",
      location: "New Delhi",
      established: "1953",
      beds: "380",
      summary:
        "Manipal Hospitals is India's foremost multispeciality healthcare provider for both national and international patients. They are a part of Manipal Education and Medical Group (MEMG). With a network of 37 hospitals in 19 cities, Manipal Hospitals is the second-largest hospital group in India. Manipal Hospital Dwarka is equipped with cutting-edge infrastructure, 24/7 emergency and trauma services, 380 beds with 13 modular advanced OTs, 118 critical care beds, with technological advancements such as an automated pneumatic acute system, telemedicine, artificial intelligence, and virtual reality.",
      departments: [
        "Cardiology",
        "Neurology",
        "Orthopedics",
        "Oncology",
        "Gastroenterology",
        "Nephrology",
      ],
      specialities: [
        "Cardiac Care",
        "Neurology & Neurosurgery",
        "Orthopedics & Joint Replacement",
        "Cancer Care",
        "Kidney Transplant",
        "Robotic Surgery",
        "Emergency & Trauma Care",
      ],
      facilities: [
        "380 Beds",
        "118 Critical Care Beds",
        "13 Modular Advanced OTs",
        "24/7 Emergency & Trauma",
        "Telemedicine Services",
        "Automated Pneumatic Acute System",
        "AI & Virtual Reality Technology",
        "Blood Bank",
      ],
      awards: [
        "Second-largest hospital group in India",
        "Cutting-edge healthcare infrastructure recognition",
      ],
      procedures: [
        "Heart Surgery",
        "Angioplasty",
        "Brain Surgery",
        "Knee & Hip Replacement",
        "Cancer Treatment",
        "Kidney Transplant",
        "Robotic Surgery",
        "Spine Surgery",
      ],
    }),
  },
  {
    slug: "max-shalimar-bagh",
    name: "Max Super Speciality Hospital Shalimar Bagh",
    location: "New Delhi",
    established: "2011",
    beds: "402",
    city: "Delhi",
    image: "/images/hospitals/max-shalimar-bagh.jpg",
    summary:
      "Advanced healthcare facility with 37+ specialities, 402 beds, treating over 4,00,000 patients worldwide with advanced technology and expert staff.",
    profile: createHospitalProfile({
      name: "Max Super Speciality Hospital Shalimar Bagh",
      location: "New Delhi",
      established: "2011",
      beds: "402",
      summary:
        "Max Super Specialty is an advanced healthcare facility offering various services in medical disciplines of cancer, cardiac sciences, neurosciences, gastroenterology, orthopedics, and renal transplant. The Max Institute of Cancer Care has the latest technology in radiation therapy, including TrueBeam Linear Accelerator capable of IMRT, IGRT, and Stereotactic RT. The hospital has experience in treating over 4,00,000 patients worldwide. With 37+ specialities, it provides the advantages of integrated medical care in a multidisciplinary setting.",
      departments: [
        "Cardiology",
        "Oncology",
        "Neurosciences",
        "Orthopedics",
        "Gastroenterology",
        "Nephrology",
      ],
      specialities: [
        "Cancer Care",
        "Cardiac Sciences",
        "Neurology & Neurosurgery",
        "Orthopedics & Joint Replacement",
        "Liver & Kidney Transplant",
        "Bariatric Surgery",
        "Radiation Oncology",
        "Robotic Surgery",
      ],
      facilities: [
        "402 Beds",
        "TrueBeam Linear Accelerator",
        "HDR Brachytherapy",
        "Advanced MRI & CT Imaging",
        "NABH & NABL Accredited",
        "24/7 Emergency",
        "Intensive Care Units",
        "Blood Bank",
      ],
      awards: [
        "NABH Accreditation",
        "NABL Accreditation",
      ],
      procedures: [
        "Radiation Therapy (IMRT, IGRT, SRS)",
        "Chemotherapy",
        "Heart Bypass Surgery",
        "Angioplasty",
        "Brain Tumor Surgery",
        "Spine Surgery",
        "Knee & Hip Replacement",
        "Liver & Kidney Transplant",
      ],
    }),
  },
  {
    slug: "medanta-gurugram",
    name: "Medanta - The Medicity Hospital",
    location: "Gurugram",
    established: "2009",
    beds: "1300+",
    city: "Gurugram",
    image: "/images/hospitals/medanta-gurugram.jpg",
    summary:
      "One of India's best multispeciality healthcare providers, recognized as the best private hospital in India for four consecutive years (2020-2023).",
    profile: createHospitalProfile({
      name: "Medanta - The Medicity Hospital",
      location: "Gurugram",
      established: "2009",
      beds: "1300+",
      summary:
        "Founded by Dr. Naresh Trehan, a renowned cardiovascular and cardiothoracic surgeon, Medanta is one of India's best multispeciality healthcare providers. For four consecutive years, Medanta Gurugram has been recognized as the best private hospital in India (2020-2023). In 2023, it was listed among the top 250 hospitals around the world by Newsweek. Medanta's patient-first approach allows a team of expert doctors to collaborate seamlessly and create a treatment plan for each patient in line with their guiding philosophy, 'Every Life is Invaluable'.",
      departments: [
        "Cardiology & CTVS",
        "Oncology",
        "Neurology & Neurosurgery",
        "Orthopedics",
        "Gastroenterology",
        "Transplant Services",
      ],
      specialities: [
        "Cardiac Surgery",
        "Cancer Care",
        "Neurology & Neurosurgery",
        "Orthopedics & Joint Replacement",
        "Liver Transplant",
        "Kidney Transplant",
        "Robotic Surgery",
        "Spine Surgery",
      ],
      facilities: [
        "1300+ Beds",
        "Multi-super-speciality Facility",
        "Advanced Robotic Surgery Suite",
        "24/7 Emergency & Trauma",
        "Comprehensive ICU",
        "Blood Bank",
        "Pharmacy",
        "International Patient Services",
      ],
      awards: [
        "Best Private Hospital in India (2020-2023)",
        "Listed among top 250 hospitals worldwide by Newsweek (2023)",
      ],
      procedures: [
        "Heart Bypass Surgery",
        "Heart Valve Replacement",
        "Angioplasty",
        "Chemotherapy & Radiation",
        "Brain Tumor Surgery",
        "Spine Surgery",
        "Knee & Hip Replacement",
        "Liver & Kidney Transplant",
      ],
    }),
  },
];
