export interface CountryPhoneCode {
  code: string;
  name: string;
  flag: string;
  localeCode: string;
}

export const countryPhoneCodes: CountryPhoneCode[] = [
  { code: "+93", name: "Afghanistan", flag: "AF", localeCode: "AF" },
  { code: "+355", name: "Albania", flag: "AL", localeCode: "AL" },
  { code: "+213", name: "Algeria", flag: "DZ", localeCode: "DZ" },
  { code: "+1-684", name: "American Samoa", flag: "AS", localeCode: "AS" },
  { code: "+376", name: "Andorra", flag: "AD", localeCode: "AD" },
  { code: "+244", name: "Angola", flag: "AO", localeCode: "AO" },
  { code: "+1-264", name: "Anguilla", flag: "AI", localeCode: "AI" },
  { code: "+1-268", name: "Antigua and Barbuda", flag: "AG", localeCode: "AG" },
  { code: "+54", name: "Argentina", flag: "AR", localeCode: "AR" },
  { code: "+374", name: "Armenia", flag: "AM", localeCode: "AM" },
  { code: "+297", name: "Aruba", flag: "AW", localeCode: "AW" },
  { code: "+61", name: "Australia", flag: "AU", localeCode: "AU" },
  { code: "+43", name: "Austria", flag: "AT", localeCode: "AT" },
  { code: "+994", name: "Azerbaijan", flag: "AZ", localeCode: "AZ" },
  { code: "+1-242", name: "Bahamas", flag: "BS", localeCode: "BS" },
  { code: "+973", name: "Bahrain", flag: "BH", localeCode: "BH" },
  { code: "+880", name: "Bangladesh", flag: "BD", localeCode: "BD" },
  { code: "+1-246", name: "Barbados", flag: "BB", localeCode: "BB" },
  { code: "+375", name: "Belarus", flag: "BY", localeCode: "BY" },
  { code: "+32", name: "Belgium", flag: "BE", localeCode: "BE" },
  { code: "+501", name: "Belize", flag: "BZ", localeCode: "BZ" },
  { code: "+229", name: "Benin", flag: "BJ", localeCode: "BJ" },
  { code: "+1-441", name: "Bermuda", flag: "BM", localeCode: "BM" },
  { code: "+975", name: "Bhutan", flag: "BT", localeCode: "BT" },
  { code: "+591", name: "Bolivia", flag: "BO", localeCode: "BO" },
  { code: "+387", name: "Bosnia and Herzegovina", flag: "BA", localeCode: "BA" },
  { code: "+267", name: "Botswana", flag: "BW", localeCode: "BW" },
  { code: "+55", name: "Brazil", flag: "BR", localeCode: "BR" },
  { code: "+246", name: "British Indian Ocean Territory", flag: "IO", localeCode: "IO" },
  { code: "+1-284", name: "British Virgin Islands", flag: "VG", localeCode: "VG" },
  { code: "+673", name: "Brunei", flag: "BN", localeCode: "BN" },
  { code: "+359", name: "Bulgaria", flag: "BG", localeCode: "BG" },
  { code: "+226", name: "Burkina Faso", flag: "BF", localeCode: "BF" },
  { code: "+257", name: "Burundi", flag: "BI", localeCode: "BI" },
  { code: "+855", name: "Cambodia", flag: "KH", localeCode: "KH" },
  { code: "+237", name: "Cameroon", flag: "CM", localeCode: "CM" },
  { code: "+1", name: "Canada", flag: "CA", localeCode: "CA" },
  { code: "+238", name: "Cape Verde", flag: "CV", localeCode: "CV" },
  { code: "+1-345", name: "Cayman Islands", flag: "KY", localeCode: "KY" },
  { code: "+236", name: "Central African Republic", flag: "CF", localeCode: "CF" },
  { code: "+235", name: "Chad", flag: "TD", localeCode: "TD" },
  { code: "+56", name: "Chile", flag: "CL", localeCode: "CL" },
  { code: "+86", name: "China", flag: "CN", localeCode: "CN" },
  { code: "+57", name: "Colombia", flag: "CO", localeCode: "CO" },
  { code: "+269", name: "Comoros", flag: "KM", localeCode: "KM" },
  { code: "+682", name: "Cook Islands", flag: "CK", localeCode: "CK" },
  { code: "+506", name: "Costa Rica", flag: "CR", localeCode: "CR" },
  { code: "+385", name: "Croatia", flag: "HR", localeCode: "HR" },
  { code: "+53", name: "Cuba", flag: "CU", localeCode: "CU" },
  { code: "+357", name: "Cyprus", flag: "CY", localeCode: "CY" },
  { code: "+420", name: "Czech Republic", flag: "CZ", localeCode: "CZ" },
  { code: "+243", name: "DR Congo", flag: "CD", localeCode: "CD" },
  { code: "+45", name: "Denmark", flag: "DK", localeCode: "DK" },
  { code: "+253", name: "Djibouti", flag: "DJ", localeCode: "DJ" },
  { code: "+1-767", name: "Dominica", flag: "DM", localeCode: "DM" },
  { code: "+1-809", name: "Dominican Republic", flag: "DO", localeCode: "DO" },
  { code: "+593", name: "Ecuador", flag: "EC", localeCode: "EC" },
  { code: "+20", name: "Egypt", flag: "EG", localeCode: "EG" },
  { code: "+503", name: "El Salvador", flag: "SV", localeCode: "SV" },
  { code: "+240", name: "Equatorial Guinea", flag: "GQ", localeCode: "GQ" },
  { code: "+291", name: "Eritrea", flag: "ER", localeCode: "ER" },
  { code: "+372", name: "Estonia", flag: "EE", localeCode: "EE" },
  { code: "+251", name: "Ethiopia", flag: "ET", localeCode: "ET" },
  { code: "+500", name: "Falkland Islands", flag: "FK", localeCode: "FK" },
  { code: "+298", name: "Faroe Islands", flag: "FO", localeCode: "FO" },
  { code: "+679", name: "Fiji", flag: "FJ", localeCode: "FJ" },
  { code: "+358", name: "Finland", flag: "FI", localeCode: "FI" },
  { code: "+33", name: "France", flag: "FR", localeCode: "FR" },
  { code: "+594", name: "French Guiana", flag: "GF", localeCode: "GF" },
  { code: "+689", name: "French Polynesia", flag: "PF", localeCode: "PF" },
  { code: "+241", name: "Gabon", flag: "GA", localeCode: "GA" },
  { code: "+220", name: "Gambia", flag: "GM", localeCode: "GM" },
  { code: "+995", name: "Georgia", flag: "GE", localeCode: "GE" },
  { code: "+49", name: "Germany", flag: "DE", localeCode: "DE" },
  { code: "+233", name: "Ghana", flag: "GH", localeCode: "GH" },
  { code: "+350", name: "Gibraltar", flag: "GI", localeCode: "GI" },
  { code: "+30", name: "Greece", flag: "GR", localeCode: "GR" },
  { code: "+299", name: "Greenland", flag: "GL", localeCode: "GL" },
  { code: "+1-473", name: "Grenada", flag: "GD", localeCode: "GD" },
  { code: "+590", name: "Guadeloupe", flag: "GP", localeCode: "GP" },
  { code: "+1-671", name: "Guam", flag: "GU", localeCode: "GU" },
  { code: "+502", name: "Guatemala", flag: "GT", localeCode: "GT" },
  { code: "+44-1481", name: "Guernsey", flag: "GG", localeCode: "GG" },
  { code: "+224", name: "Guinea", flag: "GN", localeCode: "GN" },
  { code: "+245", name: "Guinea-Bissau", flag: "GW", localeCode: "GW" },
  { code: "+592", name: "Guyana", flag: "GY", localeCode: "GY" },
  { code: "+509", name: "Haiti", flag: "HT", localeCode: "HT" },
  { code: "+504", name: "Honduras", flag: "HN", localeCode: "HN" },
  { code: "+852", name: "Hong Kong", flag: "HK", localeCode: "HK" },
  { code: "+36", name: "Hungary", flag: "HU", localeCode: "HU" },
  { code: "+354", name: "Iceland", flag: "IS", localeCode: "IS" },
  { code: "+91", name: "India", flag: "IN", localeCode: "IN" },
  { code: "+62", name: "Indonesia", flag: "ID", localeCode: "ID" },
  { code: "+98", name: "Iran", flag: "IR", localeCode: "IR" },
  { code: "+964", name: "Iraq", flag: "IQ", localeCode: "IQ" },
  { code: "+353", name: "Ireland", flag: "IE", localeCode: "IE" },
  { code: "+44-1624", name: "Isle of Man", flag: "IM", localeCode: "IM" },
  { code: "+972", name: "Israel", flag: "IL", localeCode: "IL" },
  { code: "+39", name: "Italy", flag: "IT", localeCode: "IT" },
  { code: "+225", name: "Ivory Coast", flag: "CI", localeCode: "CI" },
  { code: "+1-876", name: "Jamaica", flag: "JM", localeCode: "JM" },
  { code: "+81", name: "Japan", flag: "JP", localeCode: "JP" },
  { code: "+44-1534", name: "Jersey", flag: "JE", localeCode: "JE" },
  { code: "+962", name: "Jordan", flag: "JO", localeCode: "JO" },
  { code: "+7", name: "Kazakhstan", flag: "KZ", localeCode: "KZ" },
  { code: "+254", name: "Kenya", flag: "KE", localeCode: "KE" },
  { code: "+686", name: "Kiribati", flag: "KI", localeCode: "KI" },
  { code: "+965", name: "Kuwait", flag: "KW", localeCode: "KW" },
  { code: "+996", name: "Kyrgyzstan", flag: "KG", localeCode: "KG" },
  { code: "+856", name: "Laos", flag: "LA", localeCode: "LA" },
  { code: "+371", name: "Latvia", flag: "LV", localeCode: "LV" },
  { code: "+961", name: "Lebanon", flag: "LB", localeCode: "LB" },
  { code: "+266", name: "Lesotho", flag: "LS", localeCode: "LS" },
  { code: "+231", name: "Liberia", flag: "LR", localeCode: "LR" },
  { code: "+218", name: "Libya", flag: "LY", localeCode: "LY" },
  { code: "+423", name: "Liechtenstein", flag: "LI", localeCode: "LI" },
  { code: "+370", name: "Lithuania", flag: "LT", localeCode: "LT" },
  { code: "+352", name: "Luxembourg", flag: "LU", localeCode: "LU" },
  { code: "+853", name: "Macau", flag: "MO", localeCode: "MO" },
  { code: "+389", name: "North Macedonia", flag: "MK", localeCode: "MK" },
  { code: "+261", name: "Madagascar", flag: "MG", localeCode: "MG" },
  { code: "+265", name: "Malawi", flag: "MW", localeCode: "MW" },
  { code: "+60", name: "Malaysia", flag: "MY", localeCode: "MY" },
  { code: "+960", name: "Maldives", flag: "MV", localeCode: "MV" },
  { code: "+223", name: "Mali", flag: "ML", localeCode: "ML" },
  { code: "+356", name: "Malta", flag: "MT", localeCode: "MT" },
  { code: "+692", name: "Marshall Islands", flag: "MH", localeCode: "MH" },
  { code: "+596", name: "Martinique", flag: "MQ", localeCode: "MQ" },
  { code: "+222", name: "Mauritania", flag: "MR", localeCode: "MR" },
  { code: "+230", name: "Mauritius", flag: "MU", localeCode: "MU" },
  { code: "+262", name: "Mayotte", flag: "YT", localeCode: "YT" },
  { code: "+52", name: "Mexico", flag: "MX", localeCode: "MX" },
  { code: "+691", name: "Micronesia", flag: "FM", localeCode: "FM" },
  { code: "+373", name: "Moldova", flag: "MD", localeCode: "MD" },
  { code: "+377", name: "Monaco", flag: "MC", localeCode: "MC" },
  { code: "+976", name: "Mongolia", flag: "MN", localeCode: "MN" },
  { code: "+382", name: "Montenegro", flag: "ME", localeCode: "ME" },
  { code: "+1-664", name: "Montserrat", flag: "MS", localeCode: "MS" },
  { code: "+212", name: "Morocco", flag: "MA", localeCode: "MA" },
  { code: "+258", name: "Mozambique", flag: "MZ", localeCode: "MZ" },
  { code: "+95", name: "Myanmar", flag: "MM", localeCode: "MM" },
  { code: "+264", name: "Namibia", flag: "NA", localeCode: "NA" },
  { code: "+674", name: "Nauru", flag: "NR", localeCode: "NR" },
  { code: "+977", name: "Nepal", flag: "NP", localeCode: "NP" },
  { code: "+31", name: "Netherlands", flag: "NL", localeCode: "NL" },
  { code: "+687", name: "New Caledonia", flag: "NC", localeCode: "NC" },
  { code: "+64", name: "New Zealand", flag: "NZ", localeCode: "NZ" },
  { code: "+505", name: "Nicaragua", flag: "NI", localeCode: "NI" },
  { code: "+227", name: "Niger", flag: "NE", localeCode: "NE" },
  { code: "+234", name: "Nigeria", flag: "NG", localeCode: "NG" },
  { code: "+683", name: "Niue", flag: "NU", localeCode: "NU" },
  { code: "+850", name: "North Korea", flag: "KP", localeCode: "KP" },
  { code: "+1-670", name: "Northern Mariana Islands", flag: "MP", localeCode: "MP" },
  { code: "+47", name: "Norway", flag: "NO", localeCode: "NO" },
  { code: "+968", name: "Oman", flag: "OM", localeCode: "OM" },
  { code: "+92", name: "Pakistan", flag: "PK", localeCode: "PK" },
  { code: "+680", name: "Palau", flag: "PW", localeCode: "PW" },
  { code: "+970", name: "Palestine", flag: "PS", localeCode: "PS" },
  { code: "+507", name: "Panama", flag: "PA", localeCode: "PA" },
  { code: "+675", name: "Papua New Guinea", flag: "PG", localeCode: "PG" },
  { code: "+595", name: "Paraguay", flag: "PY", localeCode: "PY" },
  { code: "+51", name: "Peru", flag: "PE", localeCode: "PE" },
  { code: "+63", name: "Philippines", flag: "PH", localeCode: "PH" },
  { code: "+48", name: "Poland", flag: "PL", localeCode: "PL" },
  { code: "+351", name: "Portugal", flag: "PT", localeCode: "PT" },
  { code: "+1-787", name: "Puerto Rico", flag: "PR", localeCode: "PR" },
  { code: "+974", name: "Qatar", flag: "QA", localeCode: "QA" },
  { code: "+242", name: "Republic of the Congo", flag: "CG", localeCode: "CG" },
  { code: "+262", name: "Reunion", flag: "RE", localeCode: "RE" },
  { code: "+40", name: "Romania", flag: "RO", localeCode: "RO" },
  { code: "+7", name: "Russia", flag: "RU", localeCode: "RU" },
  { code: "+250", name: "Rwanda", flag: "RW", localeCode: "RW" },
  { code: "+590", name: "Saint Barthelemy", flag: "BL", localeCode: "BL" },
  { code: "+290", name: "Saint Helena", flag: "SH", localeCode: "SH" },
  { code: "+1-869", name: "Saint Kitts and Nevis", flag: "KN", localeCode: "KN" },
  { code: "+1-758", name: "Saint Lucia", flag: "LC", localeCode: "LC" },
  { code: "+590", name: "Saint Martin", flag: "MF", localeCode: "MF" },
  { code: "+508", name: "Saint Pierre and Miquelon", flag: "PM", localeCode: "PM" },
  { code: "+1-784", name: "Saint Vincent and the Grenadines", flag: "VC", localeCode: "VC" },
  { code: "+685", name: "Samoa", flag: "WS", localeCode: "WS" },
  { code: "+378", name: "San Marino", flag: "SM", localeCode: "SM" },
  { code: "+239", name: "Sao Tome and Principe", flag: "ST", localeCode: "ST" },
  { code: "+966", name: "Saudi Arabia", flag: "SA", localeCode: "SA" },
  { code: "+221", name: "Senegal", flag: "SN", localeCode: "SN" },
  { code: "+381", name: "Serbia", flag: "RS", localeCode: "RS" },
  { code: "+248", name: "Seychelles", flag: "SC", localeCode: "SC" },
  { code: "+232", name: "Sierra Leone", flag: "SL", localeCode: "SL" },
  { code: "+65", name: "Singapore", flag: "SG", localeCode: "SG" },
  { code: "+1-721", name: "Sint Maarten", flag: "SX", localeCode: "SX" },
  { code: "+421", name: "Slovakia", flag: "SK", localeCode: "SK" },
  { code: "+386", name: "Slovenia", flag: "SI", localeCode: "SI" },
  { code: "+677", name: "Solomon Islands", flag: "SB", localeCode: "SB" },
  { code: "+252", name: "Somalia", flag: "SO", localeCode: "SO" },
  { code: "+27", name: "South Africa", flag: "ZA", localeCode: "ZA" },
  { code: "+82", name: "South Korea", flag: "KR", localeCode: "KR" },
  { code: "+211", name: "South Sudan", flag: "SS", localeCode: "SS" },
  { code: "+34", name: "Spain", flag: "ES", localeCode: "ES" },
  { code: "+94", name: "Sri Lanka", flag: "LK", localeCode: "LK" },
  { code: "+249", name: "Sudan", flag: "SD", localeCode: "SD" },
  { code: "+597", name: "Suriname", flag: "SR", localeCode: "SR" },
  { code: "+268", name: "Eswatini", flag: "SZ", localeCode: "SZ" },
  { code: "+46", name: "Sweden", flag: "SE", localeCode: "SE" },
  { code: "+41", name: "Switzerland", flag: "CH", localeCode: "CH" },
  { code: "+963", name: "Syria", flag: "SY", localeCode: "SY" },
  { code: "+886", name: "Taiwan", flag: "TW", localeCode: "TW" },
  { code: "+992", name: "Tajikistan", flag: "TJ", localeCode: "TJ" },
  { code: "+255", name: "Tanzania", flag: "TZ", localeCode: "TZ" },
  { code: "+66", name: "Thailand", flag: "TH", localeCode: "TH" },
  { code: "+670", name: "Timor-Leste", flag: "TL", localeCode: "TL" },
  { code: "+228", name: "Togo", flag: "TG", localeCode: "TG" },
  { code: "+690", name: "Tokelau", flag: "TK", localeCode: "TK" },
  { code: "+676", name: "Tonga", flag: "TO", localeCode: "TO" },
  { code: "+1-868", name: "Trinidad and Tobago", flag: "TT", localeCode: "TT" },
  { code: "+216", name: "Tunisia", flag: "TN", localeCode: "TN" },
  { code: "+90", name: "Turkey", flag: "TR", localeCode: "TR" },
  { code: "+993", name: "Turkmenistan", flag: "TM", localeCode: "TM" },
  { code: "+1-649", name: "Turks and Caicos Islands", flag: "TC", localeCode: "TC" },
  { code: "+688", name: "Tuvalu", flag: "TV", localeCode: "TV" },
  { code: "+1-340", name: "U.S. Virgin Islands", flag: "VI", localeCode: "VI" },
  { code: "+256", name: "Uganda", flag: "UG", localeCode: "UG" },
  { code: "+380", name: "Ukraine", flag: "UA", localeCode: "UA" },
  { code: "+971", name: "United Arab Emirates", flag: "AE", localeCode: "AE" },
  { code: "+44", name: "United Kingdom", flag: "GB", localeCode: "GB" },
  { code: "+1", name: "United States", flag: "US", localeCode: "US" },
  { code: "+598", name: "Uruguay", flag: "UY", localeCode: "UY" },
  { code: "+998", name: "Uzbekistan", flag: "UZ", localeCode: "UZ" },
  { code: "+678", name: "Vanuatu", flag: "VU", localeCode: "VU" },
  { code: "+379", name: "Vatican City", flag: "VA", localeCode: "VA" },
  { code: "+58", name: "Venezuela", flag: "VE", localeCode: "VE" },
  { code: "+84", name: "Vietnam", flag: "VN", localeCode: "VN" },
  { code: "+681", name: "Wallis and Futuna", flag: "WF", localeCode: "WF" },
  { code: "+967", name: "Yemen", flag: "YE", localeCode: "YE" },
  { code: "+260", name: "Zambia", flag: "ZM", localeCode: "ZM" },
  { code: "+263", name: "Zimbabwe", flag: "ZW", localeCode: "ZW" },
];
