export const SEO_CONFIG = {
  defaultTitle: "India Med Service | Affordable Medical Treatment & World-Class Care in India",
  titleTemplate: "%s | India Med Service",
  description: "India Med Service helps international patients find affordable medical treatment in India. Connect with top hospitals, expert doctors, and get complete visa & travel support.",
  siteName: "India Med Service",
  url: "https://indiamedservice.com",
  canonical: "https://indiamedservice.com",
  twitterHandle: "@indiamedservice",
  ogImage: "/images/og-image.jpg",
  keywords: [
    "India Med Service",
    "India Med",
    "India Med Services",
    "India Med hospital",
    "India Med treatment",
    "Medical Tourism India",
    "Affordable Medical Treatment India",
    "Top Hospitals in India",
    "Surgery in India",
    "Medical Visa India",
    "Healthcare India",
    "Best Doctors India",
    "Medical Assistance India",
  ],
  authors: [{ name: "India Med Service", url: "https://indiamedservice.com" }],
};

